(cl:defpackage speech_recognition_msgs-srv
  (:use )
  (:export
   "SPEECHRECOGNITION"
   "<SPEECHRECOGNITION-REQUEST>"
   "SPEECHRECOGNITION-REQUEST"
   "<SPEECHRECOGNITION-RESPONSE>"
   "SPEECHRECOGNITION-RESPONSE"
  ))

