// Generated by gencpp from file audio_common_msgs/AudioDataStamped.msg
// DO NOT EDIT!


#ifndef AUDIO_COMMON_MSGS_MESSAGE_AUDIODATASTAMPED_H
#define AUDIO_COMMON_MSGS_MESSAGE_AUDIODATASTAMPED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <audio_common_msgs/AudioData.h>

namespace audio_common_msgs
{
template <class ContainerAllocator>
struct AudioDataStamped_
{
  typedef AudioDataStamped_<ContainerAllocator> Type;

  AudioDataStamped_()
    : header()
    , audio()  {
    }
  AudioDataStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , audio(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::audio_common_msgs::AudioData_<ContainerAllocator>  _audio_type;
  _audio_type audio;





  typedef boost::shared_ptr< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> const> ConstPtr;

}; // struct AudioDataStamped_

typedef ::audio_common_msgs::AudioDataStamped_<std::allocator<void> > AudioDataStamped;

typedef boost::shared_ptr< ::audio_common_msgs::AudioDataStamped > AudioDataStampedPtr;
typedef boost::shared_ptr< ::audio_common_msgs::AudioDataStamped const> AudioDataStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator1> & lhs, const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.audio == rhs.audio;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator1> & lhs, const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace audio_common_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3cdd84a06846af0dca4d0434908f9d96";
  }

  static const char* value(const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3cdd84a06846af0dULL;
  static const uint64_t static_value2 = 0xca4d0434908f9d96ULL;
};

template<class ContainerAllocator>
struct DataType< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "audio_common_msgs/AudioDataStamped";
  }

  static const char* value(const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"audio_common_msgs/AudioData audio\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: audio_common_msgs/AudioData\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.audio);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioDataStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::audio_common_msgs::AudioDataStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::audio_common_msgs::AudioDataStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "audio: ";
    s << std::endl;
    Printer< ::audio_common_msgs::AudioData_<ContainerAllocator> >::stream(s, indent + "  ", v.audio);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUDIO_COMMON_MSGS_MESSAGE_AUDIODATASTAMPED_H
