// Generated by gencpp from file calibration_msgs/IntervalStatus.msg
// DO NOT EDIT!


#ifndef CALIBRATION_MSGS_MESSAGE_INTERVALSTATUS_H
#define CALIBRATION_MSGS_MESSAGE_INTERVALSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace calibration_msgs
{
template <class ContainerAllocator>
struct IntervalStatus_
{
  typedef IntervalStatus_<ContainerAllocator> Type;

  IntervalStatus_()
    : header()
    , names()
    , yeild_rates()  {
    }
  IntervalStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , names(_alloc)
    , yeild_rates(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _yeild_rates_type;
  _yeild_rates_type yeild_rates;





  typedef boost::shared_ptr< ::calibration_msgs::IntervalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calibration_msgs::IntervalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct IntervalStatus_

typedef ::calibration_msgs::IntervalStatus_<std::allocator<void> > IntervalStatus;

typedef boost::shared_ptr< ::calibration_msgs::IntervalStatus > IntervalStatusPtr;
typedef boost::shared_ptr< ::calibration_msgs::IntervalStatus const> IntervalStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calibration_msgs::IntervalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::calibration_msgs::IntervalStatus_<ContainerAllocator1> & lhs, const ::calibration_msgs::IntervalStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.names == rhs.names &&
    lhs.yeild_rates == rhs.yeild_rates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::calibration_msgs::IntervalStatus_<ContainerAllocator1> & lhs, const ::calibration_msgs::IntervalStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace calibration_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calibration_msgs::IntervalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calibration_msgs::IntervalStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calibration_msgs::IntervalStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "277fe87e9a44a07ab27c97b6b37d5898";
  }

  static const char* value(const ::calibration_msgs::IntervalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x277fe87e9a44a07aULL;
  static const uint64_t static_value2 = 0xb27c97b6b37d5898ULL;
};

template<class ContainerAllocator>
struct DataType< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calibration_msgs/IntervalStatus";
  }

  static const char* value(const ::calibration_msgs::IntervalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Status of interval intersection\n"
"# This can give some indication of which samples have failed to capture\n"
"Header header\n"
"string[] names\n"
"float32[] yeild_rates\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::calibration_msgs::IntervalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.names);
      stream.next(m.yeild_rates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntervalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calibration_msgs::IntervalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calibration_msgs::IntervalStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "yeild_rates[]" << std::endl;
    for (size_t i = 0; i < v.yeild_rates.size(); ++i)
    {
      s << indent << "  yeild_rates[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.yeild_rates[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALIBRATION_MSGS_MESSAGE_INTERVALSTATUS_H
