(cl:defpackage joint_qualification_controllers-msg
  (:use )
  (:export
   "<ACTUATORDATA>"
   "ACTUATORDATA"
   "<CBPOSITIONDATA>"
   "CBPOSITIONDATA"
   "<CBRUNDATA>"
   "CBRUNDATA"
   "<COUNTERBALANCETESTDATA>"
   "COUNTERBALANCETESTDATA"
   "<HYSTERESISDATA>"
   "HYSTERESISDATA"
   "<HYSTERESISDATA2>"
   "HYSTERESISDATA2"
   "<HYSTERESISRUN>"
   "HYSTERESISRUN"
   "<JOINTDATA>"
   "JOINTDATA"
   "<JOINTPOSITIONDATA>"
   "JOINTPOSITIONDATA"
   "<ROBOTDATA>"
   "ROBOTDATA"
   "<WRISTDIFFDATA>"
   "WRISTDIFFDATA"
   "<WRISTROLLTURN>"
   "WRISTROLLTURN"
  ))

