// Generated by gencpp from file joint_qualification_controllers/ActuatorData.msg
// DO NOT EDIT!


#ifndef JOINT_QUALIFICATION_CONTROLLERS_MESSAGE_ACTUATORDATA_H
#define JOINT_QUALIFICATION_CONTROLLERS_MESSAGE_ACTUATORDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joint_qualification_controllers
{
template <class ContainerAllocator>
struct ActuatorData_
{
  typedef ActuatorData_<ContainerAllocator> Type;

  ActuatorData_()
    : index(0)
    , name()
    , id(0)  {
    }
  ActuatorData_(const ContainerAllocator& _alloc)
    : index(0)
    , name(_alloc)
    , id(0)  {
  (void)_alloc;
    }



   typedef int16_t _index_type;
  _index_type index;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int16_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorData_

typedef ::joint_qualification_controllers::ActuatorData_<std::allocator<void> > ActuatorData;

typedef boost::shared_ptr< ::joint_qualification_controllers::ActuatorData > ActuatorDataPtr;
typedef boost::shared_ptr< ::joint_qualification_controllers::ActuatorData const> ActuatorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator1> & lhs, const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator2> & rhs)
{
  return lhs.index == rhs.index &&
    lhs.name == rhs.name &&
    lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator1> & lhs, const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace joint_qualification_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c56db35f7889a677f83b66883afdaf4";
  }

  static const char* value(const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c56db35f7889a67ULL;
  static const uint64_t static_value2 = 0x7f83b66883afdaf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint_qualification_controllers/ActuatorData";
  }

  static const char* value(const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 index\n"
"string name\n"
"int16 id\n"
"\n"
;
  }

  static const char* value(const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.name);
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joint_qualification_controllers::ActuatorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joint_qualification_controllers::ActuatorData_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int16_t>::stream(s, indent + "  ", v.index);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOINT_QUALIFICATION_CONTROLLERS_MESSAGE_ACTUATORDATA_H
