// Generated by gencpp from file joint_states_settler/ConfigResult.msg
// DO NOT EDIT!


#ifndef JOINT_STATES_SETTLER_MESSAGE_CONFIGRESULT_H
#define JOINT_STATES_SETTLER_MESSAGE_CONFIGRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joint_states_settler
{
template <class ContainerAllocator>
struct ConfigResult_
{
  typedef ConfigResult_<ContainerAllocator> Type;

  ConfigResult_()
    {
    }
  ConfigResult_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::joint_states_settler::ConfigResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joint_states_settler::ConfigResult_<ContainerAllocator> const> ConstPtr;

}; // struct ConfigResult_

typedef ::joint_states_settler::ConfigResult_<std::allocator<void> > ConfigResult;

typedef boost::shared_ptr< ::joint_states_settler::ConfigResult > ConfigResultPtr;
typedef boost::shared_ptr< ::joint_states_settler::ConfigResult const> ConfigResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joint_states_settler::ConfigResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joint_states_settler::ConfigResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace joint_states_settler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joint_states_settler::ConfigResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joint_states_settler::ConfigResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_states_settler::ConfigResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::joint_states_settler::ConfigResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint_states_settler/ConfigResult";
  }

  static const char* value(const ::joint_states_settler::ConfigResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
;
  }

  static const char* value(const ::joint_states_settler::ConfigResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ConfigResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joint_states_settler::ConfigResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::joint_states_settler::ConfigResult_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // JOINT_STATES_SETTLER_MESSAGE_CONFIGRESULT_H
