; Auto-generated. Do not edit!


(cl:in-package joint_states_settler-msg)


;//! \htmlinclude ConfigFeedback.msg.html

(cl:defclass <ConfigFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ConfigFeedback (<ConfigFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConfigFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConfigFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name joint_states_settler-msg:<ConfigFeedback> is deprecated: use joint_states_settler-msg:ConfigFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConfigFeedback>) ostream)
  "Serializes a message object of type '<ConfigFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConfigFeedback>) istream)
  "Deserializes a message object of type '<ConfigFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConfigFeedback>)))
  "Returns string type for a message object of type '<ConfigFeedback>"
  "joint_states_settler/ConfigFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConfigFeedback)))
  "Returns string type for a message object of type 'ConfigFeedback"
  "joint_states_settler/ConfigFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConfigFeedback>)))
  "Returns md5sum for a message object of type '<ConfigFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConfigFeedback)))
  "Returns md5sum for a message object of type 'ConfigFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConfigFeedback>)))
  "Returns full string definition for message of type '<ConfigFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConfigFeedback)))
  "Returns full string definition for message of type 'ConfigFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConfigFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConfigFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ConfigFeedback
))
