; Auto-generated. Do not edit!


(cl:in-package joint_states_settler-msg)


;//! \htmlinclude ConfigActionGoal.msg.html

(cl:defclass <ConfigActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type joint_states_settler-msg:ConfigGoal
    :initform (cl:make-instance 'joint_states_settler-msg:ConfigGoal)))
)

(cl:defclass ConfigActionGoal (<ConfigActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ConfigActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ConfigActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name joint_states_settler-msg:<ConfigActionGoal> is deprecated: use joint_states_settler-msg:ConfigActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <ConfigActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader joint_states_settler-msg:header-val is deprecated.  Use joint_states_settler-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <ConfigActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader joint_states_settler-msg:goal_id-val is deprecated.  Use joint_states_settler-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <ConfigActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader joint_states_settler-msg:goal-val is deprecated.  Use joint_states_settler-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ConfigActionGoal>) ostream)
  "Serializes a message object of type '<ConfigActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ConfigActionGoal>) istream)
  "Deserializes a message object of type '<ConfigActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ConfigActionGoal>)))
  "Returns string type for a message object of type '<ConfigActionGoal>"
  "joint_states_settler/ConfigActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ConfigActionGoal)))
  "Returns string type for a message object of type 'ConfigActionGoal"
  "joint_states_settler/ConfigActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ConfigActionGoal>)))
  "Returns md5sum for a message object of type '<ConfigActionGoal>"
  "f19566577bee3cc11a5cee78c14228fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ConfigActionGoal)))
  "Returns md5sum for a message object of type 'ConfigActionGoal"
  "f19566577bee3cc11a5cee78c14228fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ConfigActionGoal>)))
  "Returns full string definition for message of type '<ConfigActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ConfigGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: joint_states_settler/ConfigGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string[] joint_names   # Names of the joints we're waiting to settle~%float64[] tolerances   # Tolerance on each of the specified joints~%duration max_step      # The maximum timestep between two elements in an interval~%uint32 cache_size      # The size of our cache when searching for an interval~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ConfigActionGoal)))
  "Returns full string definition for message of type 'ConfigActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%ConfigGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: joint_states_settler/ConfigGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string[] joint_names   # Names of the joints we're waiting to settle~%float64[] tolerances   # Tolerance on each of the specified joints~%duration max_step      # The maximum timestep between two elements in an interval~%uint32 cache_size      # The size of our cache when searching for an interval~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ConfigActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ConfigActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ConfigActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
